### ISSUE TITLE
Question: What was your submission score?

### ISSUE THREAD

**Issue by Bilgee** [5m0k3/gwd-efficientdet-pytorch#2]
Thank you for your work. 
I am curious about the submission score of the private dataset.

**Comment by 5m0k3** [comment]
The metric for the competition was mAP averaged over threshold 0.5 to 0.75 with step-size of 0.05
The test dataset had around ~1200 images and the public test dataset was the larger chunk (62%) whereas private was merely 38%, quite the opposite of usual competitions

Since there is Pseudo Labelling used in the model, every submission retrains the base model and hence producing some randomness in the final model used in prediction of test dataset. Thus, the final scores were a bit shaky

The final submission I made had the following result:
**Public: 0.7649 - 20th rank
Private: 0.6509 - 113th rank**

Can't say these were the best scores that could've been from this model as the rest of my ~200 submissions, like everybody else's, were rendered invalid because the hosts made last minute changes in the bounding boxes for private set and reran only the submitted models for everybody after the deadline
That's why you'll see that every team has only 1-2 total submissions in the leaderboard on Kaggle

You can check out my other model repository for the same competition, a YOLO V5 model, which had a **public score: 0.7769 (2nd rank at the time before non MIT license models were removed)** 
But beware, that model scored higher mainly due to the fact that the ground truth boxes in many of the images used in the competition were actually semi-automatically labelled using a YOLO V3 model

Many teams used alot different model and techniques, the final solutions posted on the Kaggle forums of this competition are worth checking out

**Comment by Bilgee** [comment]
Thank you @5m0k3 for detailed explanations. I will your check Yolov5 model. Is there any link of your yolov5 version?
